name: Run Task
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.head_ref }}

      - name: Running
        run: |
          npm cache clean --force
          npm install
          npm run task
        env:
          GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
          GOOGLE_SPREADSHEET_GID: ${{ secrets.GOOGLE_SPREADSHEET_GID }}
          TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER}}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD}}
          NODE_OPTIONS: "--max-old-space-size=8192"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update db.json
          branch: main